In [1]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv('all_files.csv')

In [4]:
df

,file_name,folder_name,submissions,weight,text,date,year_month,month
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13,2020-11,2020-11
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13,2020-11,2020-11
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13,2020-11,2020-11
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19,2020-11,2020-11
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18,2020-11,2020-11
...,...,...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27,2020-10,2020-10
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30,2020-10,2020-10
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22,2020-10,2020-10
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27,2020-10,2020-10
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27,2020-10,2020-10

In [6]:
df[df.isna().any(axis=1)]

,file_name,folder_name,submissions,weight,text,date,year_month,month
15,11-13-2- Khalili.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Zoha Khalili Sent: Friday, November 13, ...",NaN,NaN,NaT
2026,8-8-9 Itzikowitz.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...,NaN,NaN,NaT
2975,813-19 Sobel.pdf,First Field Review (June - August 2019),1,0.000018,"From: David Sobel Sent: Monday, August 12, 201...",NaN,NaN,NaT
5175,8--13-19 Hinton.pdf,First Field Review (June - August 2019),1,0.000018,"From: Karen Hinton Sent: Tuesday, August 13, 2...",NaN,NaN,NaT
6851,Gilly.pdf,Comments Received After Field Review,1,0.000017,Hi!\n\nMy name is Gilly. I'm\nIsraeli-American...,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...
7635,Luo.pdf,Comments Received After Field Review,1,0.000017,Dear California Department of Education Instru...,NaN,NaN,NaT
7638,Dahl.pdf,Comments Received After Field Review,1,0.000017,"From: Sharon Dahl\nSent: Saturday, August 17, ...",NaN,NaN,NaT
7642,Hunt.pdf,Comments Received After Field Review,1,0.000017,To: Curriculum Frameworks and Instructional Re...,NaN,NaN,NaT
7644,Gilad.pdf,Comments Received After Field Review,1,0.000017,"Hait Gilad\n\nThis curriculum is pro-BDS, negl...",NaN,NaN,NaT
7645,Moore.pdf,Comments Received After Field Review,1,0.000017,Dear California Instructional Quality Commissi...,NaN,NaN,NaT

In [7]:
df[df['text'].astype(str).str.strip() == '']

Empty DataFrame
Columns: [file_name, folder_name, submissions, weight, text, date, year_month, month]
Index: []